### ISSUE TITLE
Add REMOTE_DEBUG flag to enable Chrome DevTools

### ISSUE THREAD

**Issue by phil-d-wilson** [balenablocks/browser#12]
Discussion https://www.flowdock.com/app/rulemotion/balenalabs/threads/Wn7EZk8ww6Jng7cB95YolG1lcXo

**Comment by rahul-thakoor** [comment]
@phil-d-wilson as noted, we will remove the $DEBUG flag?
https://github.com/balenablocks/browser/blob/a53ab4ce87d08a0ba14eb51a1d7f6640a8618d3e/start.sh#L142

the information provided  is not that helpful as discussed

**Comment by phil-d-wilson** [comment]
@rahul-thakoor - I'm just wondering if it _could_ show something useful in some scenarios. I wonder if we should remove it from the readme.md so that it's not officially endorsed, but leave the functionality in the code in case we do need it!?!?

**Comment by rahul-thakoor** [comment]
your call @phil-d-wilson
