### ISSUE TITLE
Document troubleshooting using overscan settings

### ISSUE THREAD

**Issue by rahul-thakoor** [balenablocks/browser#15]
When connecting to tvs/monitors the image doesn't fit the actual full-screen size. 

--> See black borders even with window position 0,0

use: `BALENA_HOST_CONFIG_disable_overscan=1`

**Comment by phil-d-wilson** [comment]
Since you seem to have found and solved the problem - could you PR the documentation change @rahul-thakoor ?

**Comment by phil-d-wilson** [comment]
Done
