### ISSUE TITLE
Allow overriding the command that runs on start

### ISSUE THREAD

**Issue by rahul-thakoor** [balenablocks/browser#20]
https://github.com/balenablocks/browser/blob/2739c0f00933116d5e4eff4ee453dbd067702d1f/start.sh#L124

Allow changing the last command that runs in the script. E.g in balenaDash, we would rather start with tohora

This along with #17 would make it easier catering for different use cases of the browser block

**Comment by rahul-thakoor** [comment]
maybe if we can set alternative script to run @phil-d-wilson ?

e.g `ALT_START=/usr/src/app/alt_start.sh`

we could detect if the script exists then import it?

**Comment by phil-d-wilson** [comment]
Fixed in version 2
