### ISSUE TITLE
Keep command-line option for persistence seperate from FLAGS

### ISSUE THREAD

**Issue by rahul-thakoor** [balenablocks/browser#26]
https://github.com/balenablocks/browser/blob/a53ab4ce87d08a0ba14eb51a1d7f6640a8618d3e/start.sh#L71

Someone trying to keep persistence working but only modifying some other flags might have to remember to add the above option to the flags?

maybe we export ` PERSISTENT_FLAG="--user-data-dir=/data"` if we detect the variable then do 
`echo "chromium-browser $CHROME_LAUNCH_URL $FLAGS  $PERSISTENT_FLAG   --window-size=$WINDOW_SIZE --window-position=$WINDOW_POSITION $OUTPUT" >> /home/chromium/xstart.sh` here
https://github.com/balenablocks/browser/blob/a53ab4ce87d08a0ba14eb51a1d7f6640a8618d3e/start.sh#L150

**Comment by rahul-thakoor** [comment]
@phil-d-wilson I can work on this but would be grateful to get your feedback first

**Comment by phil-d-wilson** [comment]
@rahul-thakoor - yes that makes sense. Do you think we should roll this into the other enVar separation work and use this method for all of the options?!?

**Comment by rahul-thakoor** [comment]
yes 👍

**Comment by phil-d-wilson** [comment]
Fixed in version 2
