### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by Aubron** [balenablocks/browser#27]
Is this project supposed to have HDMI output audio?

Running on a raspberry pi4, with a microHDMI -> HDMI cable running to a display with internal speakers, I cannot get audio to function.

I see we usermod chromium into the audio group, would there be more to do to support HDMI audio out?

**Comment by Aubron** [comment]
Bizarrely, this was the result of having the rpi4 hdmi out plugged into HDMI1 instead of HDMI0 - preserving for posterity.

**Comment by rjoel98** [comment]
I am having this issue when using a Raspberry Pi 3 on the 64OS. Any suggestions on how to get this functioning?
