### ISSUE TITLE
Should offer a setting to turn off the screen after a period that the touch screen is inactive.

### ISSUE THREAD

**Issue by thgreasi** [balenablocks/browser#30]
User wanted to be able to specify an inactive timeout after which their touchscreen should turn off, and wake on the next user input.

**Comment by grahammcculloch** [comment]
Bump to trigger JF sync

**Comment by phil-d-wilson** [comment]
Closing as this is not a block level function, since it should be agnostic of screens attached and power management functions. This is also implemented in the balenaDash project.
