### ISSUE TITLE
All browser window can't be seen

### ISSUE THREAD

**Issue by yildirimmurat** [balenablocks/browser#31]
![IMG_2334](https://user-images.githubusercontent.com/19557293/96118537-f080ac00-0eeb-11eb-92d5-7ebf9d3bc121.JPG)
Hey All,
I am using this block as a service on my Raspberry Pi 4 to get display from a custom url. However, I always get top left corner part of the website. Even when I try to change WINDOW_SIZE at start.sh bash file, that only makes the display bigger but, still get only a part of the site.
Is there any other configuration that I miss?

**Comment by phil-d-wilson** [comment]
@yildirimmurat Hi - can you paste in your docker-compose? Your browser window doesn't look how I expect it from the block running on the Pi4 - is that a photo of the browser block running on the Pi?

**Comment by batjeciftci** [comment]
@yildirimmurat any updates, I'm also facing this problem.

**Comment by batjeciftci** [comment]
Fixed by setting window size variable to: 1920x1080

**Comment by phil-d-wilson** [comment]
Closing this, as there's no reply from the OP. Feel free to contact me if you are stilling having this issue though.
