### ISSUE TITLE
Half of screen is black, chromium kiosk

### ISSUE THREAD

**Issue by batjeciftci** [balenablocks/browser#34]
The issue can be found on this thread from the balena forums[link](https://forums.balena.io/t/half-of-screen-black-chromium-kiosk/203673/6) .

Does anyone have a fix?

**Comment by phil-d-wilson** [comment]
Fixed in the forum by increasing GPU memory:
https://forums.balena.io/t/half-of-screen-black-chromium-kiosk/203673/13
