### ISSUE TITLE
Support screensaver / power-save mode

### ISSUE THREAD

**Issue by sgrimm** [balenablocks/browser#44]
It'd be nice if there were a config option to set an idle timer so the screen powers down if there's no user interaction for a certain amount of time.

**Comment by phil-d-wilson** [comment]
Hi @sgrimm - our balenaDash project uses this browser block, and adds in another container called Scheduler, which does exactly what you're looking for:

https://github.com/balenalabs/balena-dash/tree/master/scheduler

HTH
