### ISSUE TITLE
Suppress Error Messages Created by Killing Service

### ISSUE THREAD

**Issue by borland502** [balenablocks/browser#51]
Thank you for this seed project.  I have two mild bugs and/or suggestions:  

In many kiosk instructions, there will be the following mild hack

```
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' /home/pi/.config/chromium/Default/Preferences
sed -i 's/"exit_type":"Crashed"/"exit_type":"Normal"/' /home/pi/.config/chromium/Default/Preferences
```

so that when you deploy again you won't get an offer to "restore tabs".  I'd also suggest 

```
--noerrdialogs \
--disable-infobars \
```

to gain even more real estate in "kiosk" mode.

**Comment by phil-d-wilson** [comment]
Hey there @borland502 - thanks for the suggestions.

There is a version 2 of this block about to be released any day, and it does remove the "Restore tabs" dialogue, and implements the flags you suggest.

You can find the source here: https://github.com/balenablocks/browser/tree/V2
Or feel free to try out my beta image: `phildwilson/browser:latest`
