### ISSUE TITLE
Environment variables not being passed to browser block - `su` session

### ISSUE THREAD

**Issue by danthegoodman1** [balenablocks/browser#90]
See linked JF thread, it seems like this change https://github.com/balenablocks/browser/commit/c4d9373eeb4805268ea9adbd581fabf55eb4573d does not pass the environment variables properly according to the testing that has been done in the JF thread
cc @phil-d-wilson

**Comment by kb2ma** [comment]
Looks like the command below is appending an "=" to each environment variable name in the generated list:

> $ env | grep -v -w '_' | awk -F: '{ st = index($0,"=");print substr($1,0,st) ","}' | tr -d "\n"
> SHELL=,SESSION_MANAGER=,QT_ACCESSIBILITY=,COLORTERM=, ...

Changing the argument to `awk -F` fixes it:

> $ env | grep -v -w '_' | awk -F= '{ st = index($0,"=");print substr($1,0,st) ","}' | tr -d "\n"
> SHELL,SESSION_MANAGER,QT_ACCESSIBILITY,COLORTERM,

I would think this is the format that `su -w` requires. Have not confirmed yet with a test.
