### ISSUE TITLE
change of user-dir (using PERSISTENT=1) isn't passed to chrome-launcher

### ISSUE THREAD

**Issue by o1iver** [balenablocks/browser#97]
https://github.com/balenablocks/browser/blob/af0effb01aca60f1218f1601449a66bedec2073a/src/server.js#L144

should pass the user-dir to chrome-launcher

https://github.com/GoogleChrome/chrome-launcher/blob/30755cde8627b7aad6caff1594c9752f80a39a4d/src/chrome-launcher.ts#L38

**Comment by phil-d-wilson** [comment]
Thank you for the PR! I've merged it in, but I'm doing some more fixes and will roll out a new version when I'm done..
